AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for Custom IAM Policy and Role Policy Attachments

Resources:
  PolicyCustomManaged:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: policy-dev-apse2-custom-managed-01
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: "*"
          - Effect: Deny
            Action:
              - s3:PutObject
            Resource: "*"

Outputs:
  PolicyCustomManagedOutput:
    Description: The custom managed policy
    Value: !Ref PolicyCustomManaged
